package com.heronix.scheduler.model.domain;

import com.heronix.scheduler.model.enums.EnrollmentRequestStatus;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * Course Enrollment Request Entity
 *
 * Tracks student requests to enroll in courses with priority scoring
 *
 * @author Heronix Educational Systems LLC
 * @version 2.0.0
 * @since 2025-12-21
 */
@Entity
@Table(name = "course_enrollment_requests",
       uniqueConstraints = @UniqueConstraint(columnNames = {"student_id", "course_id"}))
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CourseEnrollmentRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "student_id", nullable = false)
    private Long studentId;

    @Column(name = "course_id", nullable = false)
    private Long courseId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", insertable = false, updatable = false)
    private Student student;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", insertable = false, updatable = false)
    private Course course;

    @Column(name = "preference_rank")
    private Integer preferenceRank;

    @Column(name = "priority_score")
    private Integer priorityScore;

    @Column(name = "preference_bonus")
    private Integer preferenceBonus = 0;

    @Enumerated(EnumType.STRING)
    @Column(name = "request_status", nullable = false)
    private EnrollmentRequestStatus requestStatus = EnrollmentRequestStatus.PENDING;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "processed_at")
    private LocalDateTime processedAt;

    @Column(name = "status_reason", columnDefinition = "TEXT")
    private String statusReason;

    @Column(name = "is_waitlist")
    private Boolean isWaitlist = false;

    @Column(name = "waitlist_position")
    private Integer waitlistPosition;

    @Column(name = "manually_assigned")
    private Boolean manuallyAssigned = false;

    @Column(name = "assigned_by")
    private String assignedBy;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "academic_year_id")
    private Long academicYearId;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }

    public boolean isPending() {
        return requestStatus == EnrollmentRequestStatus.PENDING;
    }

    public boolean isApproved() {
        return requestStatus == EnrollmentRequestStatus.APPROVED ||
               requestStatus == EnrollmentRequestStatus.ALTERNATE_ASSIGNED;
    }

    public boolean isWaitlisted() {
        return requestStatus == EnrollmentRequestStatus.WAITLISTED;
    }

    public boolean isDenied() {
        return requestStatus == EnrollmentRequestStatus.DENIED;
    }

    public void approve(String reason) {
        this.requestStatus = EnrollmentRequestStatus.APPROVED;
        this.statusReason = reason;
        this.processedAt = LocalDateTime.now();
    }

    public void deny(String reason) {
        this.requestStatus = EnrollmentRequestStatus.DENIED;
        this.statusReason = reason;
        this.processedAt = LocalDateTime.now();
    }

    public void waitlist(int position, String reason) {
        this.requestStatus = EnrollmentRequestStatus.WAITLISTED;
        this.isWaitlist = true;
        this.waitlistPosition = position;
        this.statusReason = reason;
        this.processedAt = LocalDateTime.now();
    }

    /**
     * Add request to waitlist
     */
    public void addToWaitlist(int position, String reason) {
        waitlist(position, reason);
    }

    /**
     * Promote from waitlist to approved
     */
    public void promoteFromWaitlist(String reason, String promotedBy) {
        this.requestStatus = EnrollmentRequestStatus.APPROVED;
        this.isWaitlist = false;
        this.waitlistPosition = null;
        this.statusReason = reason;
        this.assignedBy = promotedBy;
        this.processedAt = LocalDateTime.now();
    }

    /**
     * Get student entity
     */
    public Student getStudent() {
        return student;
    }

    /**
     * Get course entity
     */
    public Course getCourse() {
        return course;
    }

    /**
     * Get preference bonus score
     */
    public Integer getPreferenceBonus() {
        return preferenceBonus != null ? preferenceBonus : 0;
    }

    /**
     * Calculate total priority score
     */
    public Integer getTotalPriorityScore() {
        int base = priorityScore != null ? priorityScore : 0;
        int bonus = preferenceBonus != null ? preferenceBonus : 0;
        return base + bonus;
    }
}
