package com.heronix.scheduler.model.enums;

/**
 * Enum representing the source of a substitute assignment
 *
 * @author Heronix Scheduling System Team
 * @version 1.0.0
 * @since 2025-11-05
 */
public enum AssignmentSource {

    /**
     * Assignment imported from Frontline system
     */
    FRONTLINE("Frontline", "Imported from Frontline (Kelly Services)"),

    /**
     * Assignment manually created in Heronix Scheduler
     */
    MANUAL("Manual Entry", "Manually created in system"),

    /**
     * Assignment auto-generated by system
     */
    AUTO_GENERATED("Auto-Generated", "Automatically generated by system"),

    /**
     * Assignment imported from external CSV/Excel file
     */
    IMPORT("File Import", "Imported from CSV or Excel file");

    private final String displayName;
    private final String description;

    AssignmentSource(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getDescription() {
        return description;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
